# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/property/model
# Target is a library:  

TARGETDEPS += ../../../src/property/items/libpropertyitem.a 
INCLUDEPATH += ../../../src/property/items 
MOC_DIR = .moc 
UI_DIR = .ui 
OBJECTS_DIR = .obj 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += PropertyModel.h 
SOURCES += PropertyModel.cpp 
