# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sample/sample02
# Target is an application:  

TARGETDEPS += ../../../src/property/libqproperty.a 
LIBS += ../../../src/property/libqproperty.a 
INCLUDEPATH += ../../../src/property 
CONFIG += debug \
          warn_on 
TEMPLATE = app 
FORMS += sample02.ui 
HEADERS += mainform.h 
SOURCES += sample01.cpp \
           mainform.cpp 
