# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sample
# Target is a subdirs project 

SUBDIRS += sample02 
CONFIG += release \
warn_on
TEMPLATE = subdirs
