# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/property/delegate
# Target is a subdirs project 

SUBDIRS += renderers \
           editors \
           core 
MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj
TARGET = propertydelegate
CONFIG += release \
warn_on
TEMPLATE = subdirs
