# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/property/view
# Target is a subdirs project 

SUBDIRS += treebrowser 
CONFIG += release \
warn_on
TEMPLATE = subdirs
