# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/property
# Target is a subdirs project 

SUBDIRS += items \
           model \
           view \
           core \
           delegate \
           lib 
CONFIG += release \
warn_on
TEMPLATE = subdirs
