# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += property \
           sample 
CONFIG += release \
warn_on
TEMPLATE = subdirs
