# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/property/view/treebrowser
# Target is a library:  

HEADERS += PropertyTreeBrowser.h 
SOURCES += PropertyTreeBrowser.cpp 
MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
